- name: Destroy VM on OpenStack
  hosts: all
  gather_facts: true
  tasks:
    - name: kubeadm reset cluster
      command: kubeadm reset -f
    
    - name: ensure a list of kubernetes and dockert  packages removed
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - docker
        - docker-ce
        - kubeadm
      when: ansible_os_family == 'RedHat'
    - name: remove kubernetes packages
      package:
        name: "{{ item }}"
        state: absent
      with_items:
        - kubelet
        - kubeadm
        - kubectl
        - docker.io
      when: ansible_os_family == 'Debian'

    - name: remove kubernetes metadata
      command: sudo rm -rf ~/.kube

    - name: remove docker metadata
      command: sudo rm -rf /var/lib/docker


