---
- import_playbook: site_ui1.yaml
- import_playbook: site_ui2.yaml
- import_playbook: site_ui3.yaml
- import_playbook: site_ui4.yaml
- import_playbook: site_ui5.yaml
- import_playbook: site_ui6.yaml
- import_playbook: site_ui7.yaml

