---

- hosts: kubernetes-master-nodes
  tasks:
  - name: kubectl services
    shell: kubectl get svc $(kubectl get services | awk '{print $1}' | grep -e "orion") -o yaml | grep "clusterIP" | sed -e 's/.*://'
    register: orion

  - name: copy output to local file
    copy:
      content: "{{orion.stdout}}"
      dest: "orion.txt"
    delegate_to: localhost

