"""Initial migration.

Revision ID: ffcc6166d800
Revises: 
Create Date: 2020-05-14 18:15:30.173800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffcc6166d800'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pxe_server',
    sa.Column('pxe_server_id', sa.Integer(), nullable=False),
    sa.Column('dhcp_subnet_ip', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dhcp_subnet_netmask', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dhcp_interface_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pxe_internet_interface_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dhcp_interface_ip', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dhcp_interface_netmask', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dhcp_subnet_range_begin', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dhcp_subnet_range_end', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dhcp_subnet_domain_name_servers', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pxe_server_id')
    )
    op.create_index(op.f('ix_pxe_server_created_at'), 'pxe_server', ['created_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('cluster_type', sa.String(length=20), nullable=False),
    sa.Column('cluster_os', sa.String(length=20), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_cluster_name'), 'cluster', ['cluster_name'], unique=True)
    op.create_index(op.f('ix_cluster_created_at'), 'cluster', ['created_at'], unique=False)
    op.create_table('aws_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('image_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('security_group_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('instance_type', sa.VARCHAR(length=120), nullable=False),
    sa.Column('REGION', sa.VARCHAR(length=120), nullable=False),
    sa.Column('ACCESS_KEY_ID', sa.VARCHAR(length=120), nullable=False),
    sa.Column('SECRET_ACCESS_KEY', sa.VARCHAR(length=120), nullable=False),
    sa.Column('keypair_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('key_path', sa.VARCHAR(length=400), nullable=False),
    sa.Column('vpc_subnet_id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aws_node_created_at'), 'aws_node', ['created_at'], unique=False)
    op.create_index(op.f('ix_aws_node_name'), 'aws_node', ['name'], unique=True)
    op.create_table('component',
    sa.Column('components_detail_id', sa.Integer(), nullable=False),
    sa.Column('enable_orion', sa.Boolean(), nullable=False),
    sa.Column('enable_sth_comet', sa.Boolean(), nullable=False),
    sa.Column('enable_cygnus_sth', sa.Boolean(), nullable=False),
    sa.Column('enable_iotagent', sa.Boolean(), nullable=False),
    sa.Column('enable_quantumleap', sa.Boolean(), nullable=False),
    sa.Column('enable_draco', sa.Boolean(), nullable=False),
    sa.Column('enable_ckan', sa.Boolean(), nullable=False),
    sa.Column('orion_version', sa.VARCHAR(length=120), nullable=False),
    sa.Column('mongodb_version', sa.VARCHAR(length=120), nullable=False),
    sa.Column('sth_version', sa.VARCHAR(length=120), nullable=False),
    sa.Column('sth_mongo_version', sa.VARCHAR(length=120), nullable=False),
    sa.Column('cygnus_sth_version', sa.VARCHAR(length=120), nullable=False),
    sa.Column('iot_version', sa.VARCHAR(length=120), nullable=False),
    sa.Column('quantumleap_version', sa.VARCHAR(length=120), nullable=False),
    sa.Column('crate_version', sa.VARCHAR(length=120), nullable=False),
    sa.Column('draco_version', sa.VARCHAR(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('components_detail_id')
    )
    op.create_index(op.f('ix_component_created_at'), 'component', ['created_at'], unique=False)
    op.create_table('deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_timestamp'), 'deployment', ['timestamp'], unique=False)
    op.create_table('openstack_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('flavor_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('image_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('security_group_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('keypair_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('key_path', sa.VARCHAR(length=400), nullable=False),
    sa.Column('private_network_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('external_network_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('auth_url', sa.VARCHAR(length=50), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_domain_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('project_domain_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('region_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openstack_node_created_at'), 'openstack_node', ['created_at'], unique=False)
    op.create_index(op.f('ix_openstack_node_node_name'), 'openstack_node', ['node_name'], unique=True)
    op.create_table('vm_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_name_prefix', sa.VARCHAR(length=30), nullable=False),
    sa.Column('vm_ip', sa.TEXT(length=120), nullable=False),
    sa.Column('vm_username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('vm_key_based_auth', sa.Boolean(), nullable=False),
    sa.Column('vm_password', sa.VARCHAR(length=30), nullable=True),
    sa.Column('vm_key_path', sa.VARCHAR(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vm_node_created_at'), 'vm_node', ['created_at'], unique=False)
    op.create_index(op.f('ix_vm_node_vm_name_prefix'), 'vm_node', ['vm_name_prefix'], unique=True)
    op.create_table('deployment_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('task', sa.String(length=200), nullable=True),
    sa.Column('log_type', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_log_timestamp'), 'deployment_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_log_timestamp'), table_name='deployment_log')
    op.drop_table('deployment_log')
    op.drop_index(op.f('ix_vm_node_vm_name_prefix'), table_name='vm_node')
    op.drop_index(op.f('ix_vm_node_created_at'), table_name='vm_node')
    op.drop_table('vm_node')
    op.drop_index(op.f('ix_openstack_node_node_name'), table_name='openstack_node')
    op.drop_index(op.f('ix_openstack_node_created_at'), table_name='openstack_node')
    op.drop_table('openstack_node')
    op.drop_index(op.f('ix_deployment_timestamp'), table_name='deployment')
    op.drop_table('deployment')
    op.drop_index(op.f('ix_component_created_at'), table_name='component')
    op.drop_table('component')
    op.drop_index(op.f('ix_aws_node_name'), table_name='aws_node')
    op.drop_index(op.f('ix_aws_node_created_at'), table_name='aws_node')
    op.drop_table('aws_node')
    op.drop_index(op.f('ix_cluster_created_at'), table_name='cluster')
    op.drop_index(op.f('ix_cluster_cluster_name'), table_name='cluster')
    op.drop_table('cluster')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_pxe_server_created_at'), table_name='pxe_server')
    op.drop_table('pxe_server')
    # ### end Alembic commands ###
